name: Run checker.py on PR creation

on:
  pull_request:
    types: [opened]
  workflow_dispatch:
    inputs:
      input_dir:
        description: 'Input directory for checker.py'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        ref: ${{ github.head_ref || github.ref_name }}
        repository: ${{github.event.pull_request.head.repo.full_name}}

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run checker.py
      run: python checker.py --input_dir=${{ github.event.inputs.input_dir }}
